# Generated by Django 4.2.3 on 2023-08-01 01:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contact_manager_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 8, 1, 1, 30, 24, 139738, tzinfo=datetime.timezone.utc
                ),
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
